version: '3'

services:
  sample-localstack:
    image: localstack/localstack:1.4.0
    container_name: sample-localstack
    ports:
      - 4566:4566
      - 8080:8080
    environment:
      - SERVICES=s3,sqs
      - AWS_ACCESS_KEY_ID=sample
      - AWS_SECRET_ACCESS_KEY=sample
      - AWS_DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d
